### ISSUE TITLE
Please fix for 43 

### ISSUE THREAD

**Issue by drkanukie** [kenmoore/sketch-arrange-artboards#3]
I love this plugin bit it doesn't work with 43 - its not in the list any more

**Comment by kenmoore** [comment]
@drkanukie Hi, thanks for the heads up, I submitted a request to have this plugin added back into the main plugins directory.  In the meantime, just download the latest here and it should work fine (please let me know otherwise).

**Comment by rafaelmatosdasilva** [comment]
@kenmoore it doesn't work on sketch 43. it was already listed as deprecated on 42, but worked. maybe i'm doing something wrong but the plugin isn't shown anywhere on 43. I hope you get this up and running cause your plugin is very helpful. Thank you.

**Comment by kenmoore** [comment]
Have you downloaded and installed the plugin from this Github site?  It's working for me with 43.2 (I just deleted and re-installed to test, all's good).

**Comment by rafaelmatosdasilva** [comment]
I was on 43.1 and made a few more tests and the only way to make it work was to manually add the plugin file to your user ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins

That will make it show up on the menu.

On 43.2 everything seems to be working fine. Weird. 
Either way, it's working.
Thanks a lot.

**Comment by kenmoore** [comment]
Glad to hear it!  Also, I got the updated plugin added here https://www.sketchapp.com/extensions/plugins/

Let me know if any other issues come up.  Thx

**Comment by drkanukie** [comment]
Yes resinstall and it shows up, thanks for fave plugin.
